patterns:
  - pattern: '\bapt\b'
    test-exploit-string: 'apt install malware'
    
  - pattern: '\bapt-get\b'
    test-exploit-string: 'apt-get update'
    
  - pattern: '\bapt-cache\b'
    test-exploit-string: 'apt-cache search package'
    
  - pattern: '\bapt-key\b'
    test-exploit-string: 'apt-key add key.gpg'
    
  - pattern: '\badd-apt-repository\b'
    test-exploit-string: 'add-apt-repository ppa:something'
    
  - pattern: '\bdpkg\b'
    test-exploit-string: 'dpkg -i malware.deb'
    
  - pattern: '\bsnap\b'
    test-exploit-string: 'snap install something'
    
  - pattern: '\bflatpak\b'
    test-exploit-string: 'flatpak install app'
