patterns:
  - pattern: '\bmount\b'
    test-exploit-string: 'mount /dev/sda1 /mnt'
    
  - pattern: '\bumount\b'
    test-exploit-string: 'umount /mnt'
    
  - pattern: '\bchroot\b'
    test-exploit-string: 'chroot /new/root'
    
  - pattern: '\bunshare\b'
    test-exploit-string: 'unshare -r /bin/bash'
    
  - pattern: '\bnsenter\b'
    test-exploit-string: 'nsenter -t 1 -m'
