patterns:
  - pattern: '\buseradd\b'
    test-exploit-string: 'useradd hacker'
    
  - pattern: '\buserdel\b'
    test-exploit-string: 'userdel user'
    
  - pattern: '\busermod\b'
    test-exploit-string: 'usermod -aG sudo user'
    
  - pattern: '\bgroupadd\b'
    test-exploit-string: 'groupadd admin'
    
  - pattern: '\bgroupdel\b'
    test-exploit-string: 'groupdel somegroup'
    
  - pattern: '\bgroupmod\b'
    test-exploit-string: 'groupmod -n newname oldname'
    
  - pattern: '\bpasswd\b'
    test-exploit-string: 'passwd root'
    
  - pattern: '\bchpasswd\b'
    test-exploit-string: 'echo user:pass | chpasswd'
    
  - pattern: '\badduser\b'
    test-exploit-string: 'adduser newuser'
    
  - pattern: '\bdeluser\b'
    test-exploit-string: 'deluser olduser'
