patterns:
  - pattern: '\bgcc\b'
    test-exploit-string: 'gcc exploit.c -o exploit'
    
  - pattern: 'g\+\+'
    test-exploit-string: 'g++ program.cpp -o program'
    
  - pattern: '\bcc\b'
    test-exploit-string: 'cc main.c'
    
  - pattern: '\bld\b'
    test-exploit-string: 'ld -o binary obj.o'
    
  - pattern: '\bmake\b'
    test-exploit-string: 'make install'
    
  - pattern: '\bcmake\b'
    test-exploit-string: 'cmake ..'
