patterns:
  - pattern: '\bss\b'
    test-exploit-string: 'ss -tuln'
    
  - pattern: '\bnetstat\b'
    test-exploit-string: 'netstat -an'
    
  - pattern: '\blsof\b'
    test-exploit-string: 'lsof -i :8080'
    
  - pattern: '\bps\b'
    test-exploit-string: 'ps aux'
    
  - pattern: '\btop\b'
    test-exploit-string: 'top -b -n 1'
    
  - pattern: '\bhtop\b'
    test-exploit-string: 'htop'
    
  - pattern: '\bstrace\b'
    test-exploit-string: 'strace /bin/bash'
    
  - pattern: '\bltrace\b'
    test-exploit-string: 'ltrace ls'
