patterns:
  - pattern: '/proc/'
    test-exploit-string: 'cat /proc/1/cmdline'
    
  - pattern: '/sys/'
    test-exploit-string: 'echo 1 > /sys/class/leds/led0/brightness'
    
  - pattern: '/dev/'
    test-exploit-string: 'cat /dev/sda'
    
  - pattern: '/etc/passwd'
    test-exploit-string: 'cat /etc/passwd'
    
  - pattern: '/etc/shadow'
    test-exploit-string: 'cat /etc/shadow'
    
  - pattern: '/etc/sudoers'
    test-exploit-string: 'cat /etc/sudoers'
    
  - pattern: '/root/'
    test-exploit-string: 'ls /root/.ssh'
    
  - pattern: '\.ssh/'
    test-exploit-string: 'cat ~/.ssh/id_rsa'
    
  - pattern: '\.bash_profile'
    test-exploit-string: 'echo malware >> ~/.bash_profile'
    
  - pattern: '\.bashrc'
    test-exploit-string: 'echo malware >> ~/.bashrc'
    
  - pattern: '\.profile'
    test-exploit-string: 'echo malware >> ~/.profile'
    
  - pattern: '/boot/'
    test-exploit-string: 'rm /boot/vmlinuz'
